language: go
go: "1.10.2"
services:
  - postgresql
env:
  - DEP_VERSION="0.4.1" WKSPH_ARGS_STORAGE_POSTGRES_DBNAME="wikisophia_test" WKSPH_ARGS_STORAGE_POSTGRES_USER="app_wikisophia" WKSPH_ARGS_STORAGE_POSTGRES_USER="postgres"
before_script:
  - psql -c 'create database wikisophia_test;' -U postgres
  - psql -c 'create user app_wikisophia;' -U postgres
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
script:
  - go test ./...
  - go test ./arguments/postgres -database
